In [ ]:
# What is numpy?
# core library for Scientific computing in python
# Central object in numpy "Numpy Array"
# What is numpy array?
# High Performance multidimention array object Which is
# desined specifically to perform math operation
# How many tyeps of array
# 1D -->  only rows  Axis =0  row only
# 2D -->  two axis row and column (row,column)
# 3D -->  (row,colume,axis)


In [ ]:
# sciket learn
# matplotlib
# pandas

In [ ]:
 # what ara all the different use casses and operation
 # that can be achieved easily with numpy


In [ ]:
import numpy as np
# how can we check the numpy version
np.__version__

'1.25.2'

In [ ]:
#Central object is an array
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,])
#check shape fo an array
print(type(a))
print(a.shape)
# how can you check datatypes of elements in an array
a.dtype

<class 'numpy.ndarray'>
(8,)


dtype('int64')

In [ ]:
# What is diff b\w int32 and np.int64
# what is diff b\w float32 and np.float64
# how can we find the dimensionality of array
a.ndim

1

In [ ]:
# how can i see the size of an array
a.size

8

In [ ]:
# how can i see the size in bytes in each element in an array
a.itemsize

8

In [ ]:
# Essential methods in an array
b=np.array([1,2,3])
print(b[0])
b[0]=5
print(b[0])

1
5


In [ ]:
# do element wise math opeartion
c = b * np.array([2,0,2])
print(c)

[10  0  6]


In [ ]:
# Array vs List
l= [1,2,3,4,5,6,7,8,9]
d=np.array(l)
print(d)
print(l)

# addan atom at the end of List
l.append(10)
print(l)

# there are three ways to add the items in the array
# addan atom at the end of Array
d=np.append(d,10)
print(d)

l2=l +[11]
print(l2)

[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [ ]:
a2=d + np.array([10])
print(a2)
# add the 10 number in each number of an array

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
# vector addition
# Addition of two array of same size\
a3 =a + np.array([1,2,3,4,5,6,7,8])
print(a3)

[ 2  4  6  8 10 12 14 16]


In [ ]:
# multiplication of an array
a3 =a * np.array([19])
print(a3)
#How can we do the multiplication of each element in an array

[ 19  38  57  76  95 114 133 152]


In [ ]:
a1 = np.array([1,2,3,4,5,6,7,8])
print(a1*2)

[ 2  4  6  8 10 12 14 16]


In [ ]:
# modify each atom in list and store it in new list do the
# multiply with 2 in given list

In [ ]:
# in=[2,4,8,12,16]
# out=[4,8,16,24,32]
print(a)
print(a**2)

[1 2 3 4 5 6 7 8]
[ 1  4  9 16 25 36 49 64]


In [ ]:
# To print square root of a1
print(a**0.5)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712]


In [ ]:
np.exp(a1) # All Exponantionam function What is Exponantional
np.tanh(a1) #


array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03])

In [ ]:
# How to find log of a1 by using numpy
d1=np.log(a1)
print(d1)

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154]


In [ ]:
# dot product of numpy array
a = np.array([1,2])
b = np.array([4,5])
# print(np.dot(a,b))
# Sum of the product of correspoinding entries
# multiply each corresponding element and take the sum
# cumbersome way of lists
dot = 0
for i in range(len(a)):
  dot+=a[i]* b[i]
print(dot)
print(np.dot(a,b))

14
14


In [ ]:
# step by step procedure
c=a*b
print(c)
d=np.sum(c)
print(d)

[ 4 10]
14


In [ ]:
dot =a.dot(b)
print(dot)

14


In [ ]:
dot = (a * b).sum()
print(dot)

14


In [ ]:
# in newer version
dot =a @ b
print(dot)

14


In [ ]:
import numpy as np
from timeit import default_timer as timer
a=np.random.rand(1000)
b=np.random.rand(1000)
# print(a)
# print(b)
A=list(a)
B=list(b)
T=1000
# by using List
def dot1():
  dot=0
  for i in range(len(A)):
    dot+=A[i]+B[i]
  return dot

# BY using Array list
def dot2():
  return np.dot(a,b)

# calculate time of execution
start =timer()
for t in range(T):
  dot1()
end=timer()
t1=end-start

start =timer()
for t in range(T):
  dot2()
end=timer()
t2=end-start


print("Time with Lists ",t1 )
print("Time with array ",t2)
print("ration",t1/t2)

Time with Lists  0.3416589099999925
Time with array  0.001678858999994759
ration 203.5066137186381


In [ ]:
#MUltidimensionl array

In [ ]:
a=np.array([[1,2],[4,5]])
print(a)
print("Shape",a.shape)
print("Dimension",a.ndim)
print("Size ",a.size)
print("item SIze ",a.itemsize)
print("Data type ",a.dtype)

[[1 2]
 [4 5]]
Shape (2, 2)
Dimension 2
Size  4
item SIze  8
Data type  int64


In [ ]:
print(a[0])
print(a[1,0])
print(a[1,1])


[1 2]
4
5


In [ ]:
print(a[[0]])
print(a[0,:])

[[1 2]]
[1 2]


In [ ]:
# to Print 1st colume
print(a[:,0])

# print all the colume in row 0
print(a[0,:])

[1 4]
[1 2]


In [ ]:
# Print all colume in row1
print(a[1,:])


[4 5]


In [ ]:
# Transpose
a.T

array([[1, 4],
       [2, 5]])

In [ ]:
# matrix multiplication with dot
b=np.array([[3,4],[5,6]])
print(a.dot(b))
# matrix multiplication ?
# determinante in numpy array ?
# what is determinant ?
# find the det of c ?
z=np.linalg.det(a)
print(z)

[[13 16]
 [37 46]]
-2.9999999999999996


In [ ]:
# Print inverse of array a?
c= np.linalg.inv(a)
print(c)

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [ ]:
# What is inverse
# what is matrix and all funtion of it
# do the diagonal of vector return diagonal matrix
# what is two vector
c=np.diag([1,4])
print(c)

[[1 0]
 [0 4]]


In [ ]:
# Indexing,Slicing and Boolean indexing

In [ ]:
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.size)
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(a.dtype)

12
(1, 3, 4)
3
8
int64


In [ ]:
# Print he 1,2,3,4
print(a[0,:])

[1 2 3 4]


In [ ]:
import numpy as np
# 3D array peint the 1st row of element
a = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])
first_row = a[0, 0, :]
print(first_row)
print("\n")
# de serilization-dot to line
# serialization  line to dot
print(a)

[1 2 3 4]


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [ ]:
print(a[:,0])

[[1 2 3 4]]


In [ ]:
# slicing [2,3 and 6,7]
s=a[0,0:2,1:3]
print(s)

[[2 3]
 [6 7]]


In [ ]:
print(A[-1,-2]) # ---- -ve ro eform reverse diresction "-1" and -ve colume in last position '-1'


11


In [ ]:
# boolean indexing
b= np.array([[1,2],[3,4],[5,6]])
print(b)


[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# print the value true if it is greater than 2 else false
print(b>2)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# note this will be a rank 1 array
# i want to go print greater than 2
print(b[b>2])

[3 4 5 6]


In [ ]:
z=np.where(b>2,b,-1)
print(z)  # (condition ,array,vales to be passed )

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [ ]:
# fancy indexing ----> to print the multiple indexes at once
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a[[1,3,6]])

[2 4 7]


In [ ]:
# compute indices where the condition true
print(a)
even= np.argwhere(a%2==0)
print(even)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
[[0 0 1]
 [0 0 3]
 [0 1 1]
 [0 1 3]
 [0 2 1]
 [0 2 3]]


In [ ]:
# reshaping of an array
a=np.arange(1,13)
print(a)
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(a.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1
8
int64


In [ ]:
c=a.reshape(3,4)
print(c)
print(c.shape)
print(c.ndim)
print(c.itemsize)
print(c.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
8
int64


In [ ]:
# new wax : is used to create a new axis in the data
# it is required when the data to be shaped in a manner
print(a.shape)
print(a[np.newaxis,:]) # [row()
print(a[:,np.newaxis])
#

(12,)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [ ]:
# Concatenation of array
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[4,5]])
print(np.concatenate((a,b),axis =None))


[1 2 3 4 4 5 4 5]


In [ ]:
print(np.concatenate((a,b),axis =0))
# Axis

[[1 2]
 [3 4]
 [4 5]
 [4 5]]


In [ ]:
print(np.concatenate((a,b),axis =1))


[[1 2 4 5]
 [3 4 4 5]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5]])
c=np.concatenate((a,b.T),axis =1)
print(c)

[[1 2 4]
 [3 4 5]]


In [ ]:
#hstack:- stack of array in sequence  horizentally (colume wise) need tuple
a=np.array([[1,2,3,4]])
b=np.array([[4,5,4,5]])
c=np.hstack((a,b))
print(c)
np.concatenate((a,b),axis =None)

[[1 2 3 4 4 5 4 5]]


array([1, 2, 3, 4, 4, 5, 4, 5])

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[4,5]])
c=np.hstack((a,b))
print(c)

[[1 2 4 5]
 [3 4 4 5]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[4,5]])
c=np.vstack((b,a))
print(c)

[[4 5]
 [4 5]
 [1 2]
 [3 4]]


In [ ]:
import numpy as np

a = np.array([[1, 2,4],
              [3, 4,6]])
b = np.array([[5, 6,7],
              [7, 8,9]])

result_axis_0 = np.concatenate((a, b), axis=1)

print(result_axis_0)


[[1 2 4 5 6 7]
 [3 4 6 7 8 9]]


In [ ]:
# What is
# fancy
# escape character \ :- print illegal character

In [ ]:
a='gutte'
b=int(a)
print(b)

ValueError: invalid literal for int() with base 10: 'gutte'

In [ ]:
import numpy as np
# Broadcasting
# it a powerful mechaish that allow's numpy array to work with different shape
# when performaing arthamatic operations
# function as argument eg map function accept function as a argument
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
y = np.array([1, 0, 1])   # add y to each row of x using the broad casting
print(x+y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
# Function and axis
a = np.array([[7,8,9,10,11,12,13],[17,18,19,20,21,22,23]])
print(a.sum())
print(a.sum(axis =None)) # default
print(a.sum(axis =0))
print(a.sum(axis =1))

print(a.mean())     # default
print(a.mean(axis=0))
print(a.mean(axis=1))

210
210
[24 26 28 30 32 34 36]
[ 70 140]
15.0
[12. 13. 14. 15. 16. 17. 18.]
[10. 20.]


In [ ]:
x=np.array([1,2])
print(x.dtype)


# let np choice datatype
y=np.array([1.0,2.0])
print(y.dtype)


int64
float64


In [ ]:
# force a data types how many bits you want (how Precise)
z=np.array([1,2],dtype=np.int32)
print(z.dtype)

z=np.array([1,2],dtype=np.float32)
print(z.dtype)
print(z)

int32
float32
[1. 2.]


In [ ]:
# copying
a=np.array([1,2,3])
b=a     # only copy references distribu the orignal arrray
b[0]=100
print(a)

In [ ]:
a=np.array([1,2,3])
b=a.copy()   # actual copy donot distrib the original array by using copy function
b[0]=100
print(a)

In [ ]:
# Generative array
# print zeros in 2 row and 3 columns
a=np.zeros((2,3))
print(a)

# specific number of matrix in 3 row and 3 columns
c=np.full((3,3),(5))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
# print identy matrix
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# linespace :- use to to seprate the given data into specific number
e=np.linspace(0,10,6)
print(e)

[ 0.  2.  4.  6.  8. 10.]


In [ ]:
# Random number Unifor distribution 0-1
a=np.random.randn((3,2))
print(a)

[[0.9435574  0.99924852]
 [0.24008553 0.17519134]
 [0.13415054 0.41924904]]


In [ ]:
b=np.random.randn(3,2) #normal/gussian distribution ,mean 0 and unit variance.
print(b)                    # variance =distance between two data points one data to another data
print(b)                    #

[[-0.96106634 -1.17979527]
 [ 0.65797651  0.78462316]
 [-0.56690471 -1.45642081]]


In [ ]:
c=np.random.randn(100000)
print(c.mean())
print(c.std())
print(c.var())

0.00124306712127509
0.9997452541132915
0.9994905731220498


In [ ]:
d=np.random.randn(10,3)
print(d)
print(d.mean(),d.std(),d.var())

[[-0.27387733 -1.13204145 -0.1373632 ]
 [ 1.16398084 -1.5596406   0.35704919]
 [-1.55626264 -0.32053538  0.89020233]
 [-0.75592109  0.72284487  0.56664624]
 [ 0.40981875  1.22178309  0.92310706]
 [ 0.73219953 -0.63836559 -0.77893231]
 [ 0.35939058 -0.41596434 -1.89218083]
 [-1.15905881 -1.44064305  1.38477344]
 [-1.12040132  0.29801643  0.63891611]
 [ 0.01921286  0.48112415 -0.47585999]]
-0.11626608324473545 0.9148708125464481 0.8369886036493982


In [ ]:
d=np.random.randint(3,10, size=(3,3))
print(d)
print(d.mean(),d.std(),d.var())

[[6 3 9]
 [7 9 8]
 [4 5 4]]
6.111111111111111 2.1314806770278754 4.54320987654321


In [ ]:
# integer between 0 up to integer exclusive
f=np.random.choice(10,size=8)
print(f)

[4 3 9 0 6 9 0 3]


In [ ]:
# integer between 0 up to integer exclusive
f=np.random.choice([1,2,3,4],size=8)
print(f)

[3 3 4 3 1 1 4 3]


In [ ]:
# LInear Algerbra (Eigenalues/solving liner system)
# linear and quadrtic quation # column vectors
a=np.array([[1,2],[3,4]])
# print(a)

print(np.linalg.eig(a))
# print(np.linalg.eigvals(a))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [ ]:
# print(eigenvectors[:,0])


In [ ]:
# A) e-vec * e-val =a * e-vector
# d = eigenvector[:,0]* Eigenalues[0]
# e=a@eigenvector[:,0]
# print(d)
# print(e)

In [ ]:
#  correct athod to compare matrix
# np.allclose(a,b)

In [ ]:
# Solving the linear system
# x1 + x2=220
# 1.5 x1 + 4 x2=5050

A= np.array([[1,1],[1.5,4]])
b=np.array([2200,5050])

# Ax = b <=> x=A -1 b

# Solving inverse is solve and less accurate
x=np.linalg.inv(A)@b # not recomded method
print(x)




[1500.  700.]
[1500.  700.]


In [ ]:
# LOading a csv file
# load it with np.loadtxt ()

In [ ]:
import numpy as np

# using loadtxt()
arr = np.loadtxt("/content/sample_data/california_housing_test.csv",
				delimiter=",", dtype=str)
display(arr)

print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)
print(arr.dtype)

array([['"longitude"', '"latitude"', '"housing_median_age"', ...,
        '"households"', '"median_income"', '"median_house_value"'],
       ['-122.050000', '37.370000', '27.000000', ..., '606.000000',
        '6.608500', '344700.000000'],
       ['-118.300000', '34.260000', '43.000000', ..., '277.000000',
        '3.599000', '176500.000000'],
       ...,
       ['-119.700000', '36.300000', '10.000000', ..., '220.000000',
        '2.289500', '62000.000000'],
       ['-117.120000', '34.100000', '40.000000', ..., '14.000000',
        '3.270800', '162500.000000'],
       ['-119.630000', '34.420000', '42.000000', ..., '260.000000',
        '8.560800', '500001.000000']], dtype='<U20')

27009
(3001, 9)
2
80
<U20


In [ ]:
arr = np.genfromtxt("/content/sample_data/california_housing_test.csv",
				delimiter=",", dtype=str)
display(arr)

array([['"longitude"', '"latitude"', '"housing_median_age"', ...,
        '"households"', '"median_income"', '"median_house_value"'],
       ['-122.050000', '37.370000', '27.000000', ..., '606.000000',
        '6.608500', '344700.000000'],
       ['-118.300000', '34.260000', '43.000000', ..., '277.000000',
        '3.599000', '176500.000000'],
       ...,
       ['-119.700000', '36.300000', '10.000000', ..., '220.000000',
        '2.289500', '62000.000000'],
       ['-117.120000', '34.100000', '40.000000', ..., '14.000000',
        '3.270800', '162500.000000'],
       ['-119.630000', '34.420000', '42.000000', ..., '260.000000',
        '8.560800', '500001.000000']], dtype='<U20')

In [ ]:
# simd
# numpy interview question
# numpy practice and one revision
# all the topic and aexcel cource and
# add it into linkedin
# Revision of Power bi
# numpy all 100 question solve
# CReaet login from using databse
#checker_board question is important?
